### ISSUE TITLE
All the static libraries are missing when we download the code

### ISSUE THREAD

**Issue by HarshitDaftary** [rcarlsen/Pocket-OCR#7]
![screen shot 2015-06-17 at 11 58 02 am](https://cloud.githubusercontent.com/assets/2654829/8200848/353cf5b4-14e8-11e5-804e-8316631277b1.png)

The libraries in above screenshot are missing when we download the code. Kindly help us to solve the error.

**Comment by rcarlsen** [comment]
The static libs are not included by design; download the tesseract-ocr source code and compile as described in the readme.
